/**
 * User-facing legal disclaimer text aligned with backend RESPONSE_DISCLAIMER
 * (backend/app/rag/prompts.py). Must remain visible in the UI per general.mdc.
 */
export const LEGAL_DISCLAIMER_TEXT =
  "This answer is generated by an AI assistant and is not a substitute for " +
  "licensed legal counsel. It does not constitute legal advice. Please " +
  "consult a qualified lawyer for guidance on your specific situation.";

/**
 * Default consent value for query logging, matching backend ChatRequest
 * (app/schemas/chat.py: consent_to_log defaults to True).
 */
export const DEFAULT_CONSENT_TO_LOG = true;

export const CONSENT_CHECKBOX_LABEL =
  "I consent to logging my questions for quality and audit purposes.";
